<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Zachary Binney, PhD" />


<meta name="progressive" content="true" />
<meta name="allow-skip" content="false" />

<title>Tutorial 10.1 - Data Cleaning I - General Intro</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->


<link rel="stylesheet" href="css\zb_style.css" type="text/css" />

</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-intro" class="section level2">
<h2>Intro</h2>
<p>This Tutorial continues our work on <strong>data cleaning</strong>. We’ve covered reshaping data to be tidy via pivoting and dealing with that data that may be split (or need to be split) across multiple columns.</p>
<p>Here we’re going to sort of take a step back and pretend we just found a new dataset, or received one from a colleague. What should you do immediately to familiarize yourself with it and make sure it’s in the proper condition for further analysis?</p>
<p>We’ll cover some basic, general data cleaning tasks and techniques you’ll use (or at least consider using) on pretty much any dataset you encounter in the real world: fixing incorrect or missing or implausible or corrupted or incomplete values; dealing with duplicate observations; changing variable formats; fixing variable names; and so on.</p>
<p>A warning: this Tutorial is heavier on the text than I like, with relatively less code. I’ve written a lot because I hope it can serve you as a basic guide for data cleaning moving forward.</p>
<div id="section-packages" class="section level3">
<h3>Packages</h3>
<p>As usual we need to load packages. This time we need <code>tidyverse</code> because we pretty much always do; and <code>janitor</code>, which provides some additional specialized but extremely useful cleaning functions. Remember you might need to install <code>janitor</code> first (but <code>p_load()</code> should take care of that automatically)!</p>
<p>We also need to install <code>tidyimpute</code> to give us some options for replacing missing values. That we have to install separately from Github, the code for which I’ve included below but commented out. <strong>Please be sure to run it on your own machines.</strong></p>
<p><em>Some students have had difficulty installing <code>tidyimpute</code> - if you are one of them, don’t worry about it - simply remove <code>tidyimpute</code> from out <code>p_load()</code> call, and comment out lines 693-4 and 724-5. Then proceed with the Tutorial without needing to actually run <code>tidyimpute</code>.</em></p>
<pre class="r"><code># # Install the tidyimpute package from Github
# library(devtools)
# install_github( &quot;decisionpatterns/tidyimpute&quot;)

# Load (and, if necessary, first install) packages
pacman::p_load(tidyverse, janitor, palmerpenguins, tidyimpute, fivethirtyeight)

# Stroke recovery data
stroke &lt;- read.csv(&quot;./datasets/stroke.csv&quot;)
stroke_full_raw &lt;- read.csv(&quot;./datasets/stroke_test.csv&quot;)</code></pre>
</div>
</div>
<div id="section-first-steps-with-new-datasets" class="section level2">
<h2>First Steps With New Datasets</h2>
<p>Let’s start at the beginning. You get a dataset. Now what?</p>
<p>We’re going to work with some data on stroke recovery from the Inter-University Consortium for Social and Political Research (ICPSR), an absolutely <em>massive</em> repository of shared data on a huge range of topics from researchers around the globe. Citation: Ostir, Glenn, Ottenbacher, Kenneth, and Kuo, Yong Fang. Stroke Recovery in Underserved Populations 2005-2006 [United States]. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2016-05-03. <a href="https://doi.org/10.3886/ICPSR36422.v1" class="uri">https://doi.org/10.3886/ICPSR36422.v1</a></p>
<p>The data - after being trimmed down and tidied slightly by me - is stored in the data frame <code>stroke</code>. How might you explore it? Think about what your approach would be for a moment. Consider the techniques you learned way back in Tutorial 1.1.</p>
<p>Then I’ll give you my process for getting oriented and acclimated to a new data frame.</p>
<div id="section-getting-oriented-to-new-data" class="section level3">
<h3>Getting Oriented to New Data</h3>
<p>Here’s what I like to do. I encourage you to try all this yourself on the <code>stroke</code> data in your own script as you follow along:</p>
<ul>
<li><p><code>View()</code> the data - though rather than typing that function I usually just click on it in the upper right hand pane of RStudio. This lets me get a basic idea of how the data is organized (for example, does it look wide or long?), what an individual observation might represent, the variables in the data frame, and so on.</p></li>
<li><p>Check out the structure of the data with <code>str()</code>. This gives me a quicker overview of all variables and their formats than I get by <code>View()</code>ing it.</p></li>
<li><p>Get a summary of all variables in the data frame using something like <code>summary()</code> or <code>skimr()</code>. This helps with identifying possible outliers and missing data - more on that below.</p></li>
</ul>
<div id="section-getting-oriented-to-the-stroke-data" class="section level4">
<h4>Getting Oriented to the <code>stroke</code> Data</h4>
<p>Let’s say I know just what I told you so far: this is some stroke recovery data from ICPSR. When I open the stroke data this is what I see:</p>
<div class="figure" style="text-align: center">
<img src="images/stroke_view.png" alt="Result of `View(stroke)`." width="70%" />
<p class="caption">
Result of <code>View(stroke)</code>.
</p>
</div>
<p>The first thing I notice is the first variable: <code>CASEID</code>. Stroke recovery data…what would case represent…maybe a patient? Could this be a patient identifier?</p>
<p>Let’s see if we can confirm our guess. What do you notice about the values of <code>CASEID</code>…and other variables in the data frame? Try to answer yourself how you think the data might be organized before looking below.</p>
<p><br> <br> <br></p>
<p>The first thing I notice - after the fact that they’re numbers - is that they repeat. In fact the first 6 all repeat 3 times. Do other variables that are at the level of the patient also repeat 3 times? Consider <code>AGE</code>, <code>FEMALE</code>, <code>RACE</code>, and <code>MARITAL</code> - we don’t know <em>exactly</em> what these mean yet, but they probably represent a person’s age, sex, race, and marital status. And they also repeat with <code>CASEID</code> - all the <code>CASEID</code>s that are 1 seem to refer to a 55-year old man with <code>RACE</code> = 3 and <code>MARITAL</code> = 1. So <code>CASEID</code> is, indeed, probably a patient identifier.</p>
<p>But we notice some other variables seem to <em>change</em> within a single value of <code>CASEID</code> - <code>fim</code>, <code>time</code>, and <code>cesd</code>. This cues me in to think that maybe we have multiple observations on the same stroke patient over time as they recover.</p>
<p>What about our other variables? Let’s take a look at some:</p>
<ul>
<li><p><code>NEWFAC_NUM</code> - some kind of number? Beyond that I don’t know.</p></li>
<li><p><code>AGE</code> - this one seems pretty self-explanatory. Probably the patient’s age in years. And those values make sense. Easy.</p></li>
<li><p><code>FEMALE</code> - well, OK, this is probably gender? But why are these numbers? What does <code>FEMALE = 0</code> mean? My intuition is 0 = Male and 1 = Female (0/1 is a very common No/Yes coding, and “FEMALE No” would be “Male” - with sincere apologies to our non-binary friends), but we should definitely double-check that.</p></li>
<li><p><code>RACE</code> - similar to <code>FEMALE</code>. What does <code>RACE = 3</code> mean? This one I have no intuition on at all.</p></li>
<li><p><code>DIAG_IG</code> - diagnosis of some kind? But I have no idea, really.</p></li>
<li><p><code>time</code> - maybe some measure of time since some sort of “baseline” measurement? Days seems like a sensible unit given the values of 0, 90, and 365. But this is still all guesswork!</p></li>
<li><p><code>Age.Category</code> - apparently we’re also categorizing age rather than just keeping it continuous. But what does 1 mean? It’s not 1 year old? We could probably figure this out by looking at what values of <code>AGE</code> map to which of <code>Age.Category</code>.</p>
<p><mark>Challenge:</mark> Can you figure out how to do that on your own?</p></li>
</ul>
<p>All this is guesswork so far, and it’s exhausting. Plus even the intuition I showed above is borne from <em>years</em> of working with medical data. You all probably don’t have that yet. Isn’t there a better way? Oh heck yes, there is.</p>
</div>
</div>
<div id="section-data-dictionariescodebooks" class="section level3">
<h3>Data Dictionaries/Codebooks</h3>
<p>Allow me to introduce you to the idea of <strong>data dictionaries</strong>, also known as <strong>codebooks.</strong> You’ve already seen these - just not by that name. Check out the help page for the <code>penguins</code> data frame: <code>?penguins</code>.</p>
<div class="figure" style="text-align: center">
<img src="images/penguins_data_dictionary.png" alt="Penguins data dictionary." width="70%" />
<p class="caption">
Penguins data dictionary.
</p>
</div>
<p>This help page is basically a (brief) <strong>data dictionary</strong> for <code>penguins</code>! It contains:</p>
<ol style="list-style-type: decimal">
<li><p>A brief overall description of what the data frame contains to help orient you, under “Description”</p></li>
<li><p>A list of each variable name and enough information to ensure people can understand what the data means. This can be units, or (where necessary) clarifications of numerical or other codings.</p></li>
</ol>
<p>On Canvas under the Module associated with this Tutorial there is a (once again, brief) data dictionary for the <code>stroke</code> data frame. Open it and take a look. Were our guesses above right? Do you feel like you can decipher the data better now?</p>
<p>Test your understanding of the data:</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="quiz1-1" class="tutorial-question panel-body">
<div id="quiz1-1-answer_container" class="shiny-html-output"></div>
<div id="quiz1-1-message_container" class="shiny-html-output"></div>
<div id="quiz1-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<div id="section-a-real-data-dictionarycodebook" class="section level4">
<h4>A Real Data Dictionary/Codebook</h4>
<p>The examples above are both simple, brief codebooks I’ve provided as a gentle introduction. But what if you went out and got this data in the “real world?”</p>
<p><mark>Challenge:</mark> Start by going <a href="http://doi.org/10.3886/ICPSR36422.v1">to this website</a> where I actually pulled the data. Note you might have to create a (free) account, but it’s worth it for access to this huge data repository. Then click on the “Data &amp; Documentation” tab. Then click the “Download” icon. You see a bunch of options, including <em>just</em> a Codebook or the ability to download the data in a bunch of different formats set up for different programming languages.</p>
<p>Try downloading one and opening the .zip folder you get. Can you navigate to the <strong>codebook</strong>? Open it up and take a look. It’s over 100 pages, with <em>way</em> more detail than what I provided earlier. Now <em>that’s</em> a proper codebook, y’all. That should answer just about any question any researcher could reasonably have about what they’re looking at.</p>
</div>
</div>
<div id="section-do-we-always-just-get-numbers" class="section level3">
<h3>Do We Always Just Get Numbers?</h3>
<p>The data I showed you so far had everything coded as integers. Is that always the case? Not at all. You might get something like this instead:</p>
<div class="tutorial-exercise" data-label="raw_char_data" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>head(stroke_full_raw)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>This has the benefit of being more descriptive right off the bat. But it has the drawback of being harder to process in R later. For example, you now have to deal with parsing all those strings/character data rather than having simple numbers.</p>
<p>The ideal solution would actually be to download the “R” version of the data from ICPSR, which is stored as a <code>.Rda</code> file. This can hold much more data than the <code>.csv</code>s we imported earlier. For example, it holds <code>NEWFAC_NUM</code> as a <strong>factor</strong> that is an easily-manipulated integer under the hood but <em>displays</em> as easily-readable text.</p>
<p>If you can do something like import an <code>.Rda</code>, I’d recommend that. But often you won’t have that nice option because it requires more preparation on behalf of the person sharing the data. You’re more likely to encounter a <code>.csv</code> or other file that requires some manual manipulation and re-coding on your part.</p>
</div>
</div>
<div id="section-cleaning-variable-names" class="section level2">
<h2>Cleaning Variable Names</h2>
<p>Now that we’ve learned some techniques for orienting ourselves to a data set, let’s get into some common cleaning tasks. Take a look at the variable names in <code>stroke</code>:</p>
<div class="tutorial-exercise" data-label="clean_names1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>head(stroke)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Does anything annoy you about them? It’s best for variable names to have a consistent style, and I see at least two things about these that are inconsistent. <mark>Challenge:</mark> See if you can spot them before reading below.</p>
<p><br> <br> <br></p>
<p>What I see is:</p>
<ol style="list-style-type: decimal">
<li><p>Inconsistent capitalization</p></li>
<li><p>When there are multiple words, sometimes they’re separated by <code>_</code> and sometimes by <code>.</code>.</p>
<p>Even worse, sometimes you’ll get data with <em>spaces</em> in variable names. Oh, that’s just the worst because then you have to remember to put them in backticks ``s whenever you write them in your code.</p></li>
</ol>
<p>To fix that, let me introduce you to the magical function <code>janitor::clean_names()</code>. Let’s run it:</p>
<div class="tutorial-exercise" data-label="clean_names2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>stroke %&gt;% 
  clean_names() %&gt;% 
  head()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Oh heck yeah. <em>Way</em> cleaner and more consistent. Beautiful.</p>
<p>And rather than having to change variable names manually like back in the Dark Ages, <code>clean_names()</code> does it all automatically! Seriously, you have no idea how many hours that function will save you. By default it puts everything into <code>snake_case</code>, but if you’re not a snake person you can tell it to put things in <code>camelCase</code> or some other arbitrary format if you’d like.</p>
<div id="section-the-janitor-package" class="section level3">
<h3>The <code>janitor</code> Package</h3>
<p>This package is magical. It has some very useful and time-saving functions for data cleaning tasks. I recommend <a href="https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html">reviewing the vignette on <code>janitor</code> here</a>. Bookmark it and remember it’s there for your future data cleaning needs. We’ll use it again in this Tutorial.</p>
<p>It also has some very useful functions like <code>tabyl()</code> for creating “contingency tables” (like 2x2 tables) for examining the associations between two or more categorical variables. Here’s a very simple example:</p>
<div class="tutorial-exercise" data-label="tabyl" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>stroke %&gt;% 
  tabyl(FEMALE, MARITAL)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
</div>
<div id="section-cleaning-variable-values" class="section level2">
<h2>Cleaning Variable Values</h2>
<p>Another important thing to check when you get your data is to look at the range (or levels) of values of all your variables. One easy way to do this is with <code>summary()</code>, but there are lots of other options like <code>skimr()</code>. Let’s go back to our <code>penguins</code> data:</p>
<div class="tutorial-exercise" data-label="check_vals" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>summary(penguins)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>For categorical variables (factors) like <code>species</code> and <code>island</code>, <code>summary()</code> gives us the number of observations falling into each category. For numerical variables we get a 5-number summary. For all variables we also get the number of missing observations - more on that later.</p>
<p>Just looking at variable types can cue you in to problems in your data. Is there something you think should be a number or a date or a factor but is showing as a character? Time to figure out why and correct that!</p>
<div id="section-implausible-values" class="section level3">
<h3>Implausible Values</h3>
<p>These 5-number summaries provide a nice first pass at checking for implausible values. For example, is the maximum value way way way further above the 3rd quartile than it should be based on the distribution of the rest of the data (for example, the distance between the minimum value and the 1st quartile)? Or vice versa?</p>
<p>For <code>penguins</code> I don’t really see any weird outlying values. Consider <code>flipper_length_mm</code>. The longest flippers are 231 mm, which is 18 mm higher than the 3rd quartile. Does that seem too high? Not when we compare it to the low end, where there’s an 18 mm difference between the 1st quartile and the shortest flippers, too.</p>
<p>We can also just ask ourselves do these values <em>seem</em> plausible. The shortest flippers are 172 mm, and the longest 231 mm. That’s about 7-9 inches, or maybe about 3-4 thumb lengths. You’ve all seen penguins before - does that <em>feel</em> right to you? Strikes me as OK!</p>
<p>But what if somebody’s finger slipped during data entry?</p>
<div class="tutorial-exercise" data-label="check_vals2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>penguins_error &lt;- penguins %&gt;% 
  mutate(flipper_length_mm = case_when(flipper_length_mm == 231 ~ as.integer(2231),
                                       TRUE ~ flipper_length_mm))

summary(penguins_error)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Whoops! Look at the maximum flipper length. <strong>That should immediately jump out to you as a problem in your data that needs to be addressed!</strong></p>
<div id="section-plot.-your.-data." class="section level4">
<h4>PLOT. YOUR. DATA.</h4>
<p>An even better way to check for implausible or incorrect values is to <strong>plot every single variable you are interested in working with</strong>.</p>
<p>For single categorical variables, you could do simple bar graphs, or just look at a table of counts. The same can work for multiple categorical variables, just using grouped bar graphs or “contingency tables” showing the numbers of various combinations of variable values.</p>
<p>For single continuous variables, density plots, box plots, histograms, and <a href="http://www.sthda.com/english/wiki/ggplot2-dot-plot-quick-start-guide-r-software-and-data-visualization">dot plots</a> can work well, among others like jittered scatterplots with a static y aesthetic (set to 0 or 1 or whatever you’d like). For multiple continuous variables, consider scatterplots.</p>
<p>For looking at associations between continuous and categorical variables use the techniques we’ve learned for visualizing such relationships, like joyplots.</p>
<p>As an example of how plotting can help you catch impossible values, consider these two variables:</p>
<div class="tutorial-exercise" data-label="plot_data1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># No big problems detected (though we can see we might have substantial differences by species)
penguins %&gt;% 
  ggplot(aes(x = flipper_length_mm)) +
  geom_density()

# BIG PROBLEM
classic_rock_song_list %&gt;% 
  ggplot(aes(x = release_year)) + # release_year is the year a &quot;classic rock&quot; song was released
                                  # with just a little domain knowledge, you know this should probably be roughly from 1950 and later
  geom_density()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>That second plot, on <code>release_year</code> in <code>classic_rock_song_list</code>, should cue you in <em>immediately</em> to a problem somewhere in your data. Specifically, there appears to be one (or a few, we can’t be sure yet) song(s) with a release year that is way too early. Would you have caught this if you didn’t plot it?</p>
<p>PLOT. YOUR. DATA. I cannot emphasize this enough.</p>
<p><mark>Challenge:</mark> Try redoing the above code with a boxplot and/or a dotplot, just to see how it looks.</p>
</div>
<div id="section-what-do-you-do-with-implausible-values" class="section level4">
<h4>What Do You Do With Implausible Values?</h4>
<p>The first thing is to double-check that they’re actually incorrect. Sometimes you get outliers! This should always be your first instinct, and it’s on you to investigate that possibility. Go back to your data. Plot the data. Ask the source. Is it <em>possible</em> this data is actually just a legitimate outlier?</p>
<p>If you determine it isn’t, then you have to figure out what the problem was. There are usually a couple options here:</p>
<ul>
<li><p>Data entry error (typo, mis-transcribed value from paper data, or putting the value for another variable in the wrong column)</p></li>
<li><p>Actually means “Missing” (999, 9999)</p></li>
</ul>
<p>Once you identify what situation you have, you can figure out what to do:</p>
<ul>
<li><p>If it’s actually supposed to be a missing observation, re-code it to <code>NA</code> (or however what software you’re using stores missing values; SAS, for example, uses <code>.</code>)</p></li>
<li><p>If it’s a data entry error, can you get the correct value? Think back to HW4 in QTM 150. We had a song by Elton John that said it was released in the year 1071. You can pretty well guess based on context clues or a little bit of external research that it should actually be 1971!</p>
<p>Sometimes you can ask the original source what the value <em>should</em> be.</p>
<p>Other times you can’t.</p>
<ul>
<li><p><strong>If you can determine the correct value</strong>: correct it</p></li>
<li><p><strong>If you can’t determine the correct value</strong>: you probably have to throw that value out. Set it to missing as discussed above.</p></li>
</ul></li>
</ul>
</div>
</div>
<div id="section-recoding-variable-values" class="section level3">
<h3>Recoding Variable Values</h3>
<p>Often times you’ll get data where variables aren’t quite in the format you want. Let’s talk about a couple different situations we might encounter.</p>
<div id="section-recode-categorical-variables-stored-as-numbers-to-factors" class="section level4">
<h4>Recode Categorical Variables Stored as Numbers to Factors</h4>
<p>Back to our <code>stroke</code> data! We have a bunch of numbers. From the data dictionary we know some of them are actually codes for categorical variables. We want to add the information about what category each number refers to directly to our data frame. For that we can simply create a factor:</p>
<div class="tutorial-exercise" data-label="recode_as_factor" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>stroke_recode &lt;- stroke %&gt;% 
  mutate(MARITAL = factor(MARITAL, # Change marital from its current type (integer) into a factor
                          levels = c(1, 2), # List the current values of the variable
                          labels = c(&quot;Married&quot;, &quot;Unmarried&quot;))) # Assign labels to those, in order

#Check our work
head(stroke_recode)
str(stroke_recode)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>One caution here is to not miss any levels when you’re creating your factor. If you do, those will be coerced to <code>NA</code>s - not good!</p>
</div>
<div id="section-general-value-recoding" class="section level4">
<h4>General Value Recoding</h4>
<p>For more general recoding of certain values you can use <code>recode()</code>. Here are a couple examples:</p>
<div class="tutorial-exercise" data-label="recode_general" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Recode time in months rather than days
stroke_recode &lt;- stroke %&gt;% 
  mutate(time = recode(time, 
                          &quot;90&quot; = 3L, # L to specify we want an integer to match type in our new column 
                          &quot;365&quot; = 12L)) # Even though time is an integer, we have to put each old value in quotes

#Check our work
head(stroke_recode)
str(stroke_recode)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise" data-label="recode_general2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Recode state abbreviations to full names using an outside vector
state_abbs &lt;- c(&quot;IL&quot; = &quot;Illinois&quot;, &quot;OH&quot; = &quot;Ohio&quot;, &quot;IN&quot; = &quot;Indiana&quot;, &quot;MI&quot; = &quot;Michigan&quot;, &quot;WI&quot; = &quot;Wisconsin&quot;)


midwest_recode &lt;- midwest %&gt;% 
  mutate(state = recode(state, !!!state_abbs)) # If you&#39;re passing in a vector, precede it with !!!

#Check our work
head(midwest_recode) # Now the state column is the full name!</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
<div id="section-recoding-with-joins" class="section level4">
<h4>Recoding With Joins</h4>
<p>You can also recode with joins. Here’s an example, again using our <code>midwest</code> data and state abbreviations:</p>
<div class="tutorial-exercise" data-label="recode_join" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Recode state abbreviations to full names using another data frame
state.keys &lt;- tibble(state = state.name, ab = state.abb) %&gt;%  # state.name and state.abb are vectors built in to R
  rename(state_name = state)
state.keys


midwest_recode &lt;- midwest %&gt;% 
  select(county, state, poptotal) %&gt;% # To create smaller data frame to easily see what happens
  left_join(state.keys, by = c(&quot;state&quot; = &quot;ab&quot;)) %&gt;% 
  select(-state)

#Check our work
head(midwest_recode) # Now we list states by full name!</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p><mark>Challenge:</mark> What would have happened if we <em>hadn’t</em> renamed the variable <code>state</code> from <code>state.keys</code>?</p>
</div>
<div id="section-recode-numeric-variables-stored-as-characters" class="section level4">
<h4>Recode Numeric Variables Stored as Characters</h4>
<p>What if we got a data frame like the below (surprisingly common)?</p>
<pre class="r"><code>widgets &lt;- tibble(
  factory   = c(&quot;Shenzhen&quot;, &quot;Guangdong&quot;, &quot;Shanghai&quot;, &quot;Wuhan&quot;),
  widgets_made    = c(837000, &quot;1,1200,000&quot;, 1000200, &quot;NA&quot;)
)

widgets</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["factory"],"name":[1],"type":["chr"],"align":["left"]},{"label":["widgets_made"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"Shenzhen","2":"837000"},{"1":"Guangdong","2":"1,1200,000"},{"1":"Shanghai","2":"1000200"},{"1":"Wuhan","2":"__NA__"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>What do you notice about the variable types?</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="quiz3-1" class="tutorial-question panel-body">
<div id="quiz3-1-answer_container" class="shiny-html-output"></div>
<div id="quiz3-1-message_container" class="shiny-html-output"></div>
<div id="quiz3-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<p>This mismatch happened because someone stored one of our numbers using commas even though the others didn’t have them - and because the missing value was stored as “NA” (the literal character string, an N then an A) rather than <code>NA</code> (an actual missing value). This means R will coerce the entire column (remember that term?) to the most complex data type present - in this case, a character string so it can accommodate everything that’s written.</p>
<p>How can we make <code>widgets_made</code> a numeric variable? Let’s try a very simple solution:</p>
<div class="tutorial-exercise" data-label="char_to_num2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Simple solution to make widgets_made numeric
widgets %&gt;% 
  mutate(widgets_made = as.numeric(widgets_made))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Notice any issue? Think about it for a minute before reading below.</p>
<p><br> <br> <br></p>
<p>First look at Wuhan, which had a literal character value of “NA”, is changed to <code>NA</code> since R can’t figure out how to coerce it to a number. But that’s exactly what we want in that case, so no problem.</p>
<p>Unfortunately we also lost the numeric value for Guangdong. Because it had commas, R couldn’t figure out how to automatically coerce it to a number - so it just set it to missing. To fix that we have to first remove the commas. To do that we have to learn how to manipulate and change character strings. We’ll cover that in much more detail in the next Tutorial, but for now here’s how you could accomplish it:</p>
<pre class="r"><code># Correct solution to make widgets_made numeric
widgets %&gt;% 
  mutate(widgets_made = str_replace_all(widgets_made, #Take the string widgets_made and replace every (all)...
                                    &quot;,&quot;, #...comma...
                                    &quot;&quot;)) %&gt;%  #...with nothing (no character)
  mutate(widgets_made = as.numeric(widgets_made))</code></pre>
<pre><code>## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["factory"],"name":[1],"type":["chr"],"align":["left"]},{"label":["widgets_made"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Shenzhen","2":"837000"},{"1":"Guangdong","2":"11200000"},{"1":"Shanghai","2":"1000200"},{"1":"Wuhan","2":"NA"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>That looks better now, doesn’t it? We keep Guangdong’s number. And Wuhan - which had a literal character value of “NA”, is again changed to <code>NA</code> since R can’t figure out how to coerce it to a number. But that’s exactly what we want in that case.</p>
</div>
</div>
</div>
<div id="section-duplicated-observations" class="section level2">
<h2>Duplicated Observations</h2>
<p>Another issue you’ll encounter is duplicated observations.</p>
<div id="section-identifying-duplicates" class="section level3">
<h3>Identifying Duplicates</h3>
<p>The first thing to do is identify <em>if</em> there are any duplicated observations. Once again <code>janitor</code> has an amazing function that can help here, <code>get_dupes()</code>:</p>
<div class="tutorial-exercise" data-label="get_dupes" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Insert duplicate records
penguins_dupe &lt;- rbind(penguins, penguins[300,], penguins[300,], penguins[13,])

#Check for duplicates
penguins_dupe %&gt;% 
  get_dupes()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Uh-oh! We seem to have several fully-duplicated rows (that, uh, we also created). <code>get_dupes()</code> also creates a new variable, <code>dupe_count</code>, that tells you how many times each referenced observation is duplicated. One appears a total of 3 times, the other 2 times. This is incredibly useful in larger datasets with multiple sets of duplicated observations.</p>
<p>By default, <code>get_dupes()</code> checks for rows that duplicate <em>all</em> columns. But you can also check for duplicate values on a subset of columns. Be careful here, though, because it doesn’t actually mean you have a duplicate entry! Observations share values in datasets all the time. So make sure you’ve chosen a set of columns that <em>should uniquely identify an observation first</em>.</p>
<div class="tutorial-exercise" data-label="get_dupes2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Remember penguins itself is a clean dataset with no duplicates

#Check for duplicates
penguins %&gt;% 
  get_dupes(species, island, sex, bill_length_mm, flipper_length_mm)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Even though we know there are no duplicates in this data, this code still returns 10 penguins who are part of pairs of separate penguins who just <em>happen</em> to share all these characteristics!</p>
<p>Note you could just as easily have trios or quadruplets - we just didn’t happen to here.</p>
</div>
<div id="section-dealing-with-duplicates" class="section level3">
<h3>Dealing With Duplicates</h3>
<p>Now we need to decide what we should do with any actual duplicates we identified. If we’re sure we have duplicated observations, we probably want to delete all but one copy of those duplicates. For that, I recommend <code>distinct()</code> from the <code>dplyr</code> package (part of the <code>tidyverse</code>).</p>
<div class="tutorial-exercise" data-label="deal_with_dupes" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Insert 3 duplicate records
penguins_dupe &lt;- rbind(penguins, penguins[300,], penguins[300,], penguins[13,])

str(penguins_dupe) # 347 total observations right now

#Remove duplicates (find them, then delete all but the first in each duplicate set)
penguins_dupe %&gt;% 
  distinct() # Notice we&#39;re only left with 344 rows, the correct number of unique penguins</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>What does <code>distinct()</code> do? Basically it does <code>get_dupes()</code> to identify duplicate sets (pairs, trios, quadruplets, and so on); then identifies the <em>first</em> instance of each duplicated set in the data frame; then deletes all other instances in the set. That removes all duplicates and leaves you with only one record for each…wait for it… <em>distinct</em> observation.</p>
<p>You can also use <code>distinct()</code> for subsets of columns, but the same big flashing CAUTION I listed above about accidentally identifying non-duplicate observations applies.</p>
<div class="tutorial-exercise" data-label="deal_with_dupes2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Remember penguins itself is a clean dataset with no duplicates

#Remove &quot;duplicates&quot;
penguins %&gt;% 
  distinct(species, island, sex, bill_length_mm, flipper_length_mm,
           .keep_all = TRUE) # Oh no! We should keep all 344 penguins from the original data frame,
                             # but we only have 339</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>This code identified the 10 penguins that are part of duplicated pairs, kept the first one from each pair, and deleted the other 5. Thus instead of the full dataset’s 344 penguins we’re left with 339.</p>
<p>There’s one other thing to call your attention to: the added argument <code>.keep_all = TRUE</code>. <mark>Challenge:</mark> Can you figure out what it does? Try deleting it and comparing your output - or check the <code>distinct()</code> help page.</p>
</div>
<div id="section-empty-rows-and-columns" class="section level3">
<h3>Empty Rows and Columns</h3>
<p>Yet another issue you might encounter with real world data is random empty rows or columns. This might happen if, for example, you’re dealing with poorly-kept Excel workbooks that keep different months of business data in separate “blocks” in the same spreadsheet (not that I’m speaking from experience or anything).</p>
<p>Fortunately <code>janitor()</code> makes removing these a breeze with <code>remove_empty()</code>. Here’s a simple toy example:</p>
<div class="tutorial-exercise" data-label="remove_empty" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>q &lt;- data.frame(v1 = c(1, NA, 3),
                v2 = c(NA, NA, NA),
                v3 = c(&quot;a&quot;, NA, &quot;b&quot;))
q

# Remove empty rows and columns
q_clean &lt;- q %&gt;%
  remove_empty(c(&quot;rows&quot;, &quot;cols&quot;))
q_clean

# Remove just the empty rows - for you to fill in for practice

# Remove just the empty columns - for you to fill in for practice</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
</div>
</div>
<div id="section-missing-data" class="section level2">
<h2>Missing Data</h2>
<p>Now we come to one of the biggest issues in all of data cleaning: missing data. This is a very common issue - so common, in fact, that I defy you to find a dataset outside of a class with <em>no</em> data missing. Missing data comes in a few flavors:</p>
<ol style="list-style-type: decimal">
<li><p>Missing values - that is, some rows/observations are missing data for some variables. Or some columns have some missing observations. This could also be called <strong>explicitly missing</strong> data because you’ll see an <code>NA</code> (or other value) that tells you it’s missing.</p></li>
<li><p>Entire missing observations (may be rows or columns depending on data shape) - some rows or columns are entirely missing. These are <strong>implicitly missing</strong> as no <code>NA</code> or other value will tell you it’s not there - you have to do some other checks to detect their absence.</p></li>
</ol>
<p>Let’s look at an example, with some real stock price data for Zoom in 2019 and 2020:</p>
<pre class="r"><code># Print some data on Zoom stock prices
stocks</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["qtr"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["price"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2019","2":"1","3":"NA"},{"1":"2019","2":"2","3":"62.00"},{"1":"2019","2":"3","3":"91.88"},{"1":"2019","2":"4","3":"73.55"},{"1":"2020","2":"2","3":"124.51"},{"1":"2020","2":"3","3":"245.87"},{"1":"2020","2":"4","3":"492.41"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="quiz2-1" class="tutorial-question panel-body">
<div id="quiz2-1-answer_container" class="shiny-html-output"></div>
<div id="quiz2-1-message_container" class="shiny-html-output"></div>
<div id="quiz2-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div><div class="panel panel-default">
<div data-label="quiz2-2" class="tutorial-question panel-body">
<div id="quiz2-2-answer_container" class="shiny-html-output"></div>
<div id="quiz2-2-message_container" class="shiny-html-output"></div>
<div id="quiz2-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<div id="section-how-missing-values-are-stored" class="section level3">
<h3>How “Missing” Values are Stored</h3>
<p>The “proper” way to store missing data in R is as <code>NA</code>. Recall each major vector type - logical, integer, double, and character - actually have their own kind of <code>NA</code> value. Knowing this can be important when debugging your code and interpreting error messages, though in most cases R will figure out what type of <code>NA</code> you’re dealing with automatically.</p>
<p>But when you first get your data, missing values can be represented all sorts of weird ways. Here are some examples I’ve seen:</p>
<ul>
<li><p>“Not Applicable” or “NA” (a literal character string rather than a proper <code>NA</code> value)</p></li>
<li><p><code>..</code></p></li>
<li><p><code>.</code></p></li>
<li><p><code></code> (a single space)</p></li>
<li><p>`` (a blank cell, no space)</p></li>
<li><p><code>-</code></p></li>
<li><p>A numerical code. One very common method is, for a binary yes/no variable, 0 = No; 1 = Yes; 9 = Not Applicable or Missing.</p>
<p>If instead you have a 2-digit numerical variable, 99 might represent missing.</p>
<p>For a 3-digit numerical variable, 999 might represent missing.</p>
<p>And so forth.</p></li>
</ul>
<p>Consult your <strong>data dictionary</strong> to figure out how missing values are represented in the data you receive.</p>
<p>Then my recommendation would be to <strong>recode all of those to <code>NA</code> for simplicity and consistency.</strong></p>
</div>
<div id="section-explicit-missing-values" class="section level3">
<h3>Explicit Missing Values</h3>
<p>Explicit missing values are relatively simple to deal with, because you know they’re there. I advise the following:</p>
<ul>
<li><p>Use <code>summary()</code> or another method to check how much data (how many observations) are missing for each variable.</p>
<p>If it’s a substantial amount, realize that may not be a good variable to use in any analyses. There may be some <strong>selection</strong> going on here. That is, the observations <em>with</em> data may be systematically different from those <em>without</em> it, which could bias your analysis. Or you may simply not have enough observations with data to draw any reliable conclusions about that variable.</p></li>
<li><p>Check for patterns in explicitly missing data. Are they scattered randomly? Or are most missing values clustered in just a few observations? Is most of the missing data occurring in just a handful of observations that are missing many variables?</p>
<p>This could have implications for what you do next. If the problems are clustered in a small number of observations, you might consider throwing those out. If they’re more scattered, that’s harder.</p></li>
<li><p>If you see a pattern, ask if there’s an obvious reason why those data are missing. For example, are data points at either end of a time series missing? Maybe some observation(s) in your data didn’t have values for some variables before a certain time - like Zoom not being a public company with a stock price in 2019 Q1.</p></li>
</ul>
<p>Also recognize you will also have to use <code>na.rm = TRUE</code> for many functions that act on any variable with <em>any</em> missing data. Those observations will be ignored for that function. Depending on the number of observations that are ignored, this may be OK or it may not be. It’s a judgement call for you to make - and one that you need to be aware of at all times. That’s why investigating how much data is missing and any patterns is so important.</p>
<div id="section-drop-drop_na" class="section level4">
<h4>Drop <code>drop_na()</code></h4>
<p>You may be tempted to use <code>drop_na()</code> - which drops observations with <em>any</em> missing values for the specified variables (or for <em>any</em> variable if you don’t specify any). It’s the “simplest” way to deal with missing data, and leaves you with a nice, clean, complete data frame.</p>
<p>But simple != good.</p>
<p>And I urge caution here. I don’t like simply throwing out observations without a very, very good reason. In addition to dumping the missing values, you’re also dumping a lot of useful, known, non-missing data on other variables. It’s too arbitrary and sacrifices information. Not a good practice to get into.</p>
<p>You could also induce massive bias if, for example, a subpopulation refused to answer (or couldn’t answer, because it wasn’t applicable) 1-2 questions on a survey - and you just threw out all their data entirely!</p>
<p>Plus, this could substantially reduce your sample size.</p>
<p>That said, some analyses - like regression models - require this implicitly. If you ask to regress a company’s stock price on its P/E ratio and dividends paid in the last year, then you can’t include any companies (or company-quarters) for which that information is missing. If you haven’t run a regression before this may not make sense - just move on.</p>
</div>
<div id="section-how-to-deal-with-explicit-missing-values" class="section level4">
<h4>How to Deal With Explicit Missing Values</h4>
<p>What should we do with explicit missing values? Well you have two basic choices:</p>
<ol style="list-style-type: decimal">
<li><p>Leave them missing</p></li>
<li><p>Fill them in</p></li>
</ol>
<p>Let’s discuss some options for filling them in.</p>
<div id="section-filling-in-with-prior-values" class="section level5">
<h5><strong>Filling in With Prior Values</strong></h5>
<p>Sometimes to make data entry go faster, certain fields that are repeated will be left blank, like so:</p>
<pre class="r"><code>treatment &lt;- tribble(
  ~ person,           ~ treatment, ~response,
  &quot;Derrick Whitmore&quot;, 1,           7,
  NA,                 2,           10,
  NA,                 3,           9,
  &quot;Katherine Burke&quot;,  1,           4
)

treatment</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["person"],"name":[1],"type":["chr"],"align":["left"]},{"label":["treatment"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["response"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Derrick Whitmore","2":"1","3":"7"},{"1":"NA","2":"2","3":"10"},{"1":"NA","2":"3","3":"9"},{"1":"Katherine Burke","2":"1","3":"4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The first three rows are all data on Derrick - we just left the second and third ones blank. It’s quite easy to fill them in by carrying prior values forward using the <code>fill()</code> function, also in <code>tidyverse</code>:</p>
<div class="tutorial-exercise" data-label="fill2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>treatment %&gt;% 
  fill(person) # Specify the variable name(s) you want to fill with prior values</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p><mark>Challenge:</mark> What if I wanted to fill in the blanks with “Katherine Burke” instead? Can you figure out what minor modification you would make to the code above to do that?</p>
<p>Be careful with <code>fill()</code>. Before you do it, make sure simply carrying the prior value of a variable forward makes sense for <em>all</em> the missing values of that variable. R can’t distinguish when it does and doesn’t, so it does the same thing for all of them. Whether that’s a good idea requires your judgement.</p>
</div>
<div id="section-filling-in-with-imputed-values" class="section level5">
<h5><strong>Filling in With Imputed Values</strong></h5>
<p>Another thing you can do is fill in <code>NA</code>s with sensible actual values of the variable in question. Options include:</p>
<ul>
<li><p>A static value that makes sense.</p>
<p>For example, in the <code>stroke</code> data <code>fim</code> is a measure of functioning after stroke recovery that’s sometimes missing. Maybe you talk to the original researchers and discover it’s only missing when a patient died. Then maybe it would make sense to fill those in with the minimum score for <code>fim</code> (18), or even just a flat 0. You could do that a few different ways:</p></li>
</ul>
<div class="tutorial-exercise" data-label="impute_static" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Impute 0 for missing FIM using our old friend case_when()
stroke %&gt;% 
  mutate(fim = case_when(is.na(fim) ~ as.integer(0), # To indicate FIM should stay as integers, not switch to doubles
                         TRUE ~ fim))

# Impute 0 for missing FIM using replace_na()
stroke %&gt;% 
  replace_na(list(fim = 0)) # Must enclose your recodings as a list()

# Impute 0 for missing FIM using tidyimpute::impute()
stroke %&gt;%
  impute(0, fim)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>The last method was based on the <code>tidyimpute</code> package, which despite its name is not part of the <code>tidyverse</code>. You should have installed it separately on your own machines.</p>
<p>You should be able to parse the basics of what all that code did, but to help orient you to the general structure of an <code>impute()</code> call:</p>
<pre class="r"><code>&lt;DATA FRAME WITH MISSINGS&gt; %&gt;%
    impute(&lt;REPLACEMENT VALUE&gt;,
           &lt;FIRST COLUMN WHERE MISSING VALUES WANT TO BE REPLACED&gt;,
           &lt;SECOND COLUMN WHERE MISSING VALUES WANT TO BE REPLACED&gt;,
           ...
           )</code></pre>
<p>Note if you want to impute different values for different columns you’ll need to use a separate <code>impute()</code> call.</p>
<p>I’d urge using static imputation with extreme caution. <strong>You need a really strong belief about the proper imputed value. If you’re not sure, you could really mess up your data by forcing very wrong/unrealistic values on observations.</strong></p>
<ul>
<li><p>You could, instead, simply impute all missings with the overall mean value of a variable (or the most common category if it’s categorical). This has a similar flaw as static imputation - you could assign a very wrong value to many observations! - but it may be better if there’s no particular reason for data to be missing. That is, if stroke victims were just missing <code>fim</code> data completely at random, perhaps just filling in those missings with the mean <code>fim</code> value more or less makes sense.</p>
<p>Here’s an easy way to do that using <code>tidyimpute</code>:</p></li>
</ul>
<div class="tutorial-exercise" data-label="impute_mean" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Impute mean for missing FIM using tidyimpute::impute()
stroke %&gt;%
  impute_mean(fim)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>You can also impute other summary statistics easily by using, for example, <code>impute_median()</code>.</p>
<ul>
<li>You could replace missings with the mean of a variable <em>from a particular subgroup</em>. What if you knew <code>fim</code> depended heavily on someone’s race, so you wanted to impute with the mean for their particular race? That’s slightly more complicated:</li>
</ul>
<div class="tutorial-exercise" data-label="impute_mean_subgroup" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Calculate the mean fim by racial group in a separate data frame
mean_fim_race &lt;- stroke %&gt;% 
  group_by(RACE) %&gt;% 
  summarize(mean_fim = mean(fim, na.rm = TRUE)) # Only use non-missing FIM for the mean calculations

mean_fim_race

# Link this data back into the main data frame
stroke %&gt;% 
  # Link in mean data
  left_join(mean_fim_race, by = &quot;RACE&quot;) %&gt;% 
  #Fill in missing fim values with group means
  mutate(fim = case_when(is.na(fim) ~ mean_fim, 
                         TRUE ~ as.double(fim))) %&gt;%  # To allow for decimals, make fim a double rather than integer
  # Drop new column
  select(-mean_fim)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>You could get potentially more accurate missing values by using even more fine subgroups (say by race and gender), but then you may run into small sample size problems - or even certain subgroups that don’t have any data for calculating a mean value!</p>
<p>All of this manual imputing by means is very blunt and can result in quite inaccurate values. Once again I urge you to use it with CAUTION.</p>
<p>The most sophisticated (and best) methods for imputing missing data right now involve using statistical models to predict the value of a missing observation based on its other covariates - but also doing that many times in a procedure called <strong>multiple imputation</strong>. Each imputation will give us a somewhat different value for the missing data. Then, analyzing all those data sets together lets us account for the uncertainty in our result that arises from not knowing the true value of the missing data. But how to do that - or how to implement it in R - are far beyond the scope of this course.</p>
</div>
</div>
</div>
<div id="section-implicit-missing-observations" class="section level3">
<h3>Implicit Missing Observations</h3>
<p>The big issue with implicit missing observations is identifying them and making them explicit so they can be dealt with properly. The best strategy I can offer you for this is the <code>complete()</code> function in the tidyverse. This function takes a sequence of variables, creates all possible combinations of them, and makes sure they all appear in your data frame. If one doesn’t, it creates that combination and fills in <code>NA</code>s for all the other variables. Here’s an example:</p>
<div class="tutorial-exercise" data-label="complete" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Print some data on Zoom stock prices, with the missing quarter filled in
stocks %&gt;% 
  complete(year, qtr)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>This filled in 2020 Q1 because it recognized there was a Q1 for 2019, and a year 2020, yet no entry in the data frame matching these. So it created one. And then filled in <code>price</code> - the one variable that <em>isn’t</em> <code>year</code> or <code>qtr</code> - with <code>NA</code>.</p>
<p>Choose a variable or set of variable(s) that you should have at least one observation of for every combination - like quarter and year above. Then try <code>complete()</code> on those variables to see if anything is implicitly missing.</p>
</div>
</div>
<div id="section-script.-your.-cleaning." class="section level2">
<h2>Script. Your. Cleaning.</h2>
<p>One last note before we’re done:</p>
<p>Script. Your. Cleaning.</p>
<p>What does that mean? <strong>You should always keep a copy of the totally raw, uncleaned data you got straight from the source.</strong> Then import that into an R script and do all the cleaning there. You can run your script to generate a clean data frame as often as you need. But this has two major advantages:</p>
<ol style="list-style-type: decimal">
<li><p>You can keep full track of all the changes you made (and, if you commented your code properly, why).</p></li>
<li><p>If you decide you need to undo something or revert to an older version, you always have the oldest raw version to work from. So then it’s just a matter of commenting out or changing various parts of your cleaning script. Easy.</p></li>
</ol>
</div>
<div id="section-summary" class="section level2">
<h2>Summary</h2>
<p>In this Tutorial we covered some basic, general data cleaning tasks common to most if not all datasets you’ll encounter.</p>
<p>In the next few Tutorials we’ll cover more specifically how to do cleaning and manipulation of strings (using <code>stringr</code>), factors (using <code>forcats</code>, which we’ve also covered a bit back in Tutorial 4.2), and dates (with <code>lubridate</code>).</p>

<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server-start">

# # Install the tidyimpute package from Github
# library(devtools)
# install_github( "decisionpatterns/tidyimpute")

# Load (and, if necessary, first install) packages
pacman::p_load(tidyverse, janitor, palmerpenguins, tidyimpute, fivethirtyeight)

# Stroke recovery data
stroke <- read.csv("./datasets/stroke.csv")
stroke_full_raw <- read.csv("./datasets/stroke_test.csv")


</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz1-1", question = structure("How many unmarried white females in New York rehab facilities were there?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_db5c207",     option = "0", value = "0", label = structure("0", html = TRUE, class = c("html",     "character")), correct = FALSE, message = structure("You may not have used the right filters. There <em>are<\u002fem> some of these people.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_65bda58", option = "315", value = "315",     label = structure("315", html = TRUE, class = c("html", "character"    )), correct = FALSE, message = structure("Close! Is this the number of <em>people<\u002fem>?", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ca3e1e9", option = "105", value = "105",     label = structure("105", html = TRUE, class = c("html", "character"    )), correct = TRUE, message = structure("That&#39;s right! Nice job.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_9178c34", option = "We Don't Know",     value = "We Don't Know", label = structure("We Don&#39;t Know", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz1-1-answer", question = "quiz1-1"), loading = structure("<strong>Loading:<\u002fstrong> \nHow many unmarried white females in New York rehab facilities were there?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = TRUE,     seed = 428975472.300243, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-raw_char_data-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-raw_char_data-code-editor`)), session)
output$`tutorial-exercise-raw_char_data-output` <- renderUI({
  `tutorial-exercise-raw_char_data-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-clean_names1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-clean_names1-code-editor`)), session)
output$`tutorial-exercise-clean_names1-output` <- renderUI({
  `tutorial-exercise-clean_names1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-clean_names2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-clean_names2-code-editor`)), session)
output$`tutorial-exercise-clean_names2-output` <- renderUI({
  `tutorial-exercise-clean_names2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-tabyl-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-tabyl-code-editor`)), session)
output$`tutorial-exercise-tabyl-output` <- renderUI({
  `tutorial-exercise-tabyl-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-check_vals-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-check_vals-code-editor`)), session)
output$`tutorial-exercise-check_vals-output` <- renderUI({
  `tutorial-exercise-check_vals-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-check_vals2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-check_vals2-code-editor`)), session)
output$`tutorial-exercise-check_vals2-output` <- renderUI({
  `tutorial-exercise-check_vals2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-plot_data1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-plot_data1-code-editor`)), session)
output$`tutorial-exercise-plot_data1-output` <- renderUI({
  `tutorial-exercise-plot_data1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-recode_as_factor-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-recode_as_factor-code-editor`)), session)
output$`tutorial-exercise-recode_as_factor-output` <- renderUI({
  `tutorial-exercise-recode_as_factor-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-recode_general-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-recode_general-code-editor`)), session)
output$`tutorial-exercise-recode_general-output` <- renderUI({
  `tutorial-exercise-recode_general-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-recode_general2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-recode_general2-code-editor`)), session)
output$`tutorial-exercise-recode_general2-output` <- renderUI({
  `tutorial-exercise-recode_general2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-recode_join-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-recode_join-code-editor`)), session)
output$`tutorial-exercise-recode_join-output` <- renderUI({
  `tutorial-exercise-recode_join-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz3-1", question = structure("The variable <code>widgets_made<\u002fcode> is a ______ variable, and it should probably be a _______ variable.", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_65db03b",     option = "character/numeric", value = "character/numeric",     label = structure("character/numeric", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("That&#39;s right! The quantity of widgets produced is a numeric variable, but we can see at the top of the printed table it appears to be stored as a character.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_3177609", option = "numeric/character",     value = "numeric/character", label = structure("numeric/character", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a663c81",     option = "character/character", value = "character/character",     label = structure("character/character", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ab232d3",     option = "numeric/numeric", value = "numeric/numeric", label = structure("numeric/numeric", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz3-1-answer", question = "quiz3-1"), loading = structure("<strong>Loading:<\u002fstrong> \nThe variable <code>widgets_made<\u002fcode> is a ______ variable, and it should probably be a _______ variable.\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = TRUE,     seed = 1584830484.26201, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-char_to_num2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-char_to_num2-code-editor`)), session)
output$`tutorial-exercise-char_to_num2-output` <- renderUI({
  `tutorial-exercise-char_to_num2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-get_dupes-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-get_dupes-code-editor`)), session)
output$`tutorial-exercise-get_dupes-output` <- renderUI({
  `tutorial-exercise-get_dupes-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-get_dupes2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-get_dupes2-code-editor`)), session)
output$`tutorial-exercise-get_dupes2-output` <- renderUI({
  `tutorial-exercise-get_dupes2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-deal_with_dupes-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-deal_with_dupes-code-editor`)), session)
output$`tutorial-exercise-deal_with_dupes-output` <- renderUI({
  `tutorial-exercise-deal_with_dupes-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-deal_with_dupes2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-deal_with_dupes2-code-editor`)), session)
output$`tutorial-exercise-deal_with_dupes2-output` <- renderUI({
  `tutorial-exercise-deal_with_dupes2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-remove_empty-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-remove_empty-code-editor`)), session)
output$`tutorial-exercise-remove_empty-output` <- renderUI({
  `tutorial-exercise-remove_empty-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-1", question = structure("The data on Zoom&#39;s stock price in 2019 Q1 is...", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_44b49a2",     option = "implicitly missing", value = "implicitly missing",     label = structure("implicitly missing", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_5bb460",     option = "explicitly missing", value = "explicitly missing",     label = structure("explicitly missing", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("That&#39;s right! It&#39;s in the data frame as an observation but is explicitly listed as missing with an <code>NA<\u002fcode> entry. (Metaphorical) bonus points if you can figure out why.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz2-1-answer", question = "quiz2-1"), loading = structure("<strong>Loading:<\u002fstrong> \nThe data on Zoom&#39;s stock price in 2019 Q1 is...\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = TRUE,     seed = 1101138058.48724, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-2", question = structure("What data is implicitly missing in the above data frame?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_1bfaf49",     option = "Q1 2019", value = "Q1 2019", label = structure("Q1 2019", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_62b6cf6",     option = "Q4 2020", value = "Q4 2020", label = structure("Q4 2020", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_eef7e26",     option = "Q1 2020", value = "Q1 2020", label = structure("Q1 2020", html = TRUE, class = c("html",     "character")), correct = TRUE, message = structure("Excellent. Notice we have observations for 2019 Q4 and 2020 Q2. It would stand to reason there <em>should<\u002fem> be a 2020 Q1 in between. And yet there isn&#39;t. It&#39;s missing, but...implicitly. R doesn&#39;t tell you explicitly that it&#39;s missing with an <code>NA<\u002fcode>. You had to notice it. Or do some detective work to find it.", html = TRUE, class = c("html",     "character"))), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_658c30e", option = "No data is implicitly missing",     value = "No data is implicitly missing", label = structure("No data is implicitly missing", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz2-2-answer", question = "quiz2-2"), loading = structure("<strong>Loading:<\u002fstrong> \nWhat data is implicitly missing in the above data frame?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = TRUE,     seed = 36798750.9828642, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-fill2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-fill2-code-editor`)), session)
output$`tutorial-exercise-fill2-output` <- renderUI({
  `tutorial-exercise-fill2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-impute_static-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-impute_static-code-editor`)), session)
output$`tutorial-exercise-impute_static-output` <- renderUI({
  `tutorial-exercise-impute_static-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-impute_mean-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-impute_mean-code-editor`)), session)
output$`tutorial-exercise-impute_mean-output` <- renderUI({
  `tutorial-exercise-impute_mean-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-impute_mean_subgroup-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-impute_mean_subgroup-code-editor`)), session)
output$`tutorial-exercise-impute_mean_subgroup-output` <- renderUI({
  `tutorial-exercise-impute_mean_subgroup-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-complete-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-complete-code-editor`)), session)
output$`tutorial-exercise-complete-output` <- renderUI({
  `tutorial-exercise-complete-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","cellranger","checkmate","cli","colorspace","compiler","crayon","datasets","DBI","dbplyr","digest","dplyr","ellipsis","evaluate","fansi","fastmap","fivethirtyeight","forcats","fs","generics","ggplot2","glue","graphics","grDevices","grid","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","httr","janitor","jsonlite","knitr","later","learnr","lifecycle","lubridate","magrittr","markdown","methods","mime","modelr","munsell","na.tools","pacman","palmerpenguins","pillar","pkgconfig","promises","purrr","R6","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","scales","shiny","snakecase","stats","stringi","stringr","tibble","tidyimpute","tidyr","tidyselect","tidyverse","tools","tzdb","utf8","utils","vctrs","withr","xfun","xml2","xtable","yaml"]},{"type":"character","attributes":{},"value":["0.2.1","1.1.7","4.0.2","0.7.9","1.1.0","2.0.0","3.0.1","1.4-1","4.0.2","1.4.1","4.0.2","1.1.0","2.1.1","0.6.25","1.0.7","0.3.2","0.14","0.4.1","1.0.1","0.6.1","0.5.1","1.5.0","0.0.2","3.3.5","1.4.1","4.0.2","4.0.2","4.0.2","0.3.0","2.3.1","0.8","1.1.0","0.5.0","1.5.3","1.5.4","1.4.2","2.1.0","1.7.2","1.29","1.1.0.1","0.10.1","1.0.0","1.7.10","2.0.1","1.1","4.0.2","0.9","0.1.8","0.5.0","0.3.1","0.5.1","0.1.0","1.6.2","2.0.3","1.1.1","0.3.4","2.4.1","1.0.7","2.0.0","1.3.1","2.0.0","0.4.11","2.3","1.3-2","0.13","1.0.1","1.1.1","1.5.0","0.11.0","4.0.2","1.4.6","1.4.0","3.1.3","0.2.0","1.1.3","1.1.0","1.3.1","4.0.2","0.1.2","1.1.4","4.0.2","0.3.8","2.4.2","0.22","1.3.2","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Tutorial 10.1 - Data Cleaning I - General Intro</h2>
<h4 class="author"><em>Zachary Binney, PhD</em></h4>
<h4 class="date"><em>March 2021</em></h4>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
